apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-kafka-config
  namespace: bubblemaps
data:
  kafka.xml: |
    <clickhouse>
      <kafka>
        <security_protocol>sasl_ssl</security_protocol>
        <sasl_mechanisms>PLAIN</sasl_mechanisms>
        <sasl_username from_env="KAFKA_API_KEY"/>
        <sasl_password from_env="KAFKA_API_SECRET"/>
      </kafka>
    </clickhouse>
